name: tempo_app
description: Tempo App - an app to manage your time and your sleep
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/login_bg.png
  - assets/register_bg.png

fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Bold.otf
        weight: 700
      - asset: fonts/Poppins-Medium.otf
        weight: 500
      - asset: fonts/Poppins-Regular.otf
        weight: 400
      - asset: fonts/Poppins-Semibold.otf
        weight: 600